server:
  port: 8080

spring:
  config:
    import: secrets.yaml
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: ~
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    open-in-view: false
    properties:
      hibernate.enable_lazy_load_no_trans: true